version: '3.2'

services:
  datacatalogue_backend:
    image: hbpmip/datacatalogue_spring_boot_backend:${DATACATALOGUE_VERSION}
    ports:
      - 8086:8086
    depends_on:
      - datacatalogue_postgres
    links:
      - datacatalogue_postgres
    environment:
      - spring.datasource.url=jdbc:postgresql://datacatalogue_postgres:5432/datacatalog
      - spring.datasource.username=andy
      - spring.datasource.password=password
      - keycloak.client.clientId=${KEYCLOAK_CLIENT_ID}
      - keycloak.client.clientSecret=${KEYCLOAK_CLIENT_SECRET}
      - keycloak.client.accessTokenUri=${KEYCLOAK_PROTOCOL}://${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_REALM}/protocol/openid-connect/token
      - keycloak.resource.userInfoUri=${KEYCLOAK_PROTOCOL}://${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_REALM}/protocol/openid-connect/userinfo
      - keycloak.client.userAuthorizationUri=${KEYCLOAK_PROTOCOL}://${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_REALM}/protocol/openid-connect/auth
      - keycloak.client.redirect_uri=${DATACATALOGUE_PROTOCOL}://${DATACATALOGUE_URL}
      - keycloak.client.logout_uri=${KEYCLOAK_PROTOCOL}://${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_REALM}/protocol/openid-connect/logout
    restart: on-failure

  datacataloguefrontend:
    image: hbpmip/datacatalogue_angular_frontend:${DATACATALOGUE_VERSION}
    ports:
      - 4200:4200
    depends_on:
      - datacatalogue_backend
    links:
      - datacatalogue_backend
    restart: on-failure

  datacatalogue_postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_DB=datacatalog
      - POSTGRES_USER=andy
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: on-failure

