version: '3.2'
services:

  datacatalogue_backend:
    image: hbpmip/datacatalogue_spring_boot_backend:latest
    ports:
      - 8086
    depends_on:
      - datacatalogue_postgres
    links:
      - datacatalogue_postgres
    environment:
      - spring.datasource.url=jdbc:postgresql://datacatalogue_postgres:5432/datacatalog
      - spring.datasource.username=andy
      - spring.datasource.password=password
      - keycloak.client.clientId=Mipqa
      - keycloak.client.clientSecret=a67c7ae8-e8f2-444b-a0a4-bd0b783adb47
      - keycloak.client.accessTokenUri=https://iam.humanbrainproject.eu/auth/realms/MIPTEST/protocol/openid-connect/token
      - keycloak.resource.userInfoUri=https://iam.humanbrainproject.eu/auth/realms/MIPTEST/protocol/openid-connect/userinfo
      - keycloak.client.userAuthorizationUri=https://iam.humanbrainproject.eu/auth/realms/MIPTEST/protocol/openid-connect/auth
      - keycloak.client.redirect_uri=http://localhost:4200/pathologies
    restart: on-failure

  datacatalogue_frontend:
    image: hbpmip/datacatalogue_angular_frontend:latest
    ports:
      - 4200:4200
    depends_on:
      - datacatalogue_backend
    links:
      - datacatalogue_backend
    restart: on-failure

  datacatalogue_postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_DB=datacatalog
      - POSTGRES_USER=andy
      - POSTGRES_PASSWORD=password

    volumes:
      - ./postgres_data:/var/lib/postgresql/data

    restart: on-failure
